#ifndef _CONFIG_H_
#define _CONFIG_H_

#define IP_ADDRESS "192.168.2.1"
#define RACK 0
#define SLOT 1
#define DB_INDEX 18
#define DB_SIZE 276

#define CSV_PATH "./"
#define CSV_NAME "InlineCubing"
#define CSV_SEPARATOR ';'


enum _csv_;
typedef enum _csv_ csv;

enum _csv_
{
    CSV_JOB_NUMBER=0,
    CSV_VEHICLE_NUMBER,
    CSV_REAR_WINDOW_TYPE,
    CSV_VEHICLE_MODEL,
    CSV_WINDOW_ID,
    CSV_TIME_FROM_PRIMER_APPLICATION,
    CSV_PRIMER_DETECTION_WITH_WISION,
    CSV_BEAD_CHECK_AREA,
    CSV_PRIMER_CURING_RACK,
    CSV_PRIMER_FLASHOFF_TIME,
    CSV_TIME_FROM_PRIMER_APP_UTIL_GLUE_APP,
    CSV_TIME_FROM_LAST_DISPENSE,
    CSV_TIME_GLUE_APPLICATION,
    CSV_TIME_GLUE_APPLICATION_FINISH,
    CSV_TIME_GLUE_APPLICATION_FINISH_UTIL_TAKE_OUT,
    CSV_BARREL_A_EXPIRATION,
    CSV_ADHESIVE_A_BATCH_ID,
    CSV_ADHESIVE_A_SERIAL,
    CSV_MATERIAL_A_DISPENSED,
    CSV_PISTOL_TEMPERATURE_MIN,
    CSV_PISTOL_TEMPERATURE_ACTUAL,
    CSV_PISTOL_TEMPERATURE_MAX,
    CSV_POT_A_TEMPERATURE_MIN,
    CSV_POT_A_TEMPERATURE_ACTUAL,
    CSV_POT_A_TEMPERATURE_MAX,
    CSV_BARREL_B_EXPIRATION,
    CSV_ADHESIVE_B_BATCH_ID,
    CSV_ADHESIVE_B_SERIAL,
    CSV_MATERIAL_B_DISPENSED,
    CSV_APPLICATION_RATIO,
    CSV_MIX_TUBE_LIFE,
    CSV_ROBOT_FINISH_WITHOUT_FAULT,
    CSV_DISPENSE_UNIT_FINISH_WITHOUT_FAULT,
    CSV_ROTARY_UNIT_FINISH_WITHOUT_FAULT,
    CSV_ADHESIVE_APPLICATION_PROCESS_SUMMARY,
    CSV_BEAD_CHECK_LASER_SENSOR,
    CSV_SIZE
};

#endif
